"""Locations supported for Indeed + JobStreet search (Malaysia & Singapore)."""

# Display labels (sent to scrapers as the location query string).
JOB_SEARCH_LOCATIONS: list[str] = [
    # Singapore
    "Singapore",
    "Singapore — Central",
    "Singapore — East",
    "Singapore — West",
    # Kuala Lumpur & Selangor
    "Kuala Lumpur",
    "Petaling Jaya",
    "Shah Alam",
    "Subang Jaya",
    "Puchong",
    "Klang",
    "Kajang",
    "Cheras",
    "Ampang",
    "Gombak",
    "Selayang",
    "Seri Kembangan",
    "Cyberjaya",
    "Putrajaya",
    # Other Peninsular cities
    "Penang",
    "George Town",
    "Butterworth",
    "Bukit Mertajam",
    "Ipoh",
    "Johor Bahru",
    "Iskandar Puteri",
    "Skudai",
    "Muar",
    "Melaka",
    "Malacca",
    "Seremban",
    "Kuantan",
    "Kota Bharu",
    "Alor Setar",
    "Kangar",
    "Kuala Terengganu",
    "Kuala Selangor",
    "Rawang",
    "Sepang",
    "Nilai",
    "Seremban 2",
    # East Malaysia
    "Kota Kinabalu",
    "Sandakan",
    "Tawau",
    "Kuching",
    "Miri",
    "Sibu",
    "Bintulu",
]
